module.exports = [

/* =====================================================
   🎉 COLLEGE FESTS (15)
===================================================== */

{
  externalId: "fest_mood_indigo_2025",
  title: "Mood Indigo 2025",
  organization: "Indian Institute of Technology Bombay",
  type: "college-fest",
  location: "Mumbai",
  domains: ["other"],
  prize: "Competitions, prizes, cultural exposure",
  stipend: null,
  startDate: "2025-12-19",
  deadline: "2025-12-05",
  duration: "4 days",
  link: "https://moodi.org/",
},

{
  externalId: "fest_techfest_iitb_2025",
  title: "Techfest IIT Bombay 2025",
  organization: "Indian Institute of Technology Bombay",
  type: "college-fest",
  location: "Mumbai",
  domains: ["ai/ml", "robotics", "iot"],
  prize: "Cash prizes, certificates",
  stipend: null,
  startDate: "2025-12-27",
  deadline: "2025-12-10",
  duration: "3 days",
  link: "https://techfest.org/",
},

{
  externalId: "fest_abhivyakti_vjti_2026",
  title: "Abhivyakti VJTI 2026",
  organization: "Veermata Jijabai Technological Institute",
  type: "college-fest",
  location: "Mumbai",
  domains: ["other"],
  prize: "Competitions & recognition",
  stipend: null,
  startDate: "2026-02-14",
  deadline: "2026-02-01",
  duration: "3 days",
  link: "https://abhivyaktivjti.in/",
},

{
  externalId: "fest_pratibimb_spit_2026",
  title: "Pratibimb SPIT 2026",
  organization: "Sardar Patel Institute of Technology",
  type: "college-fest",
  location: "Mumbai",
  domains: ["other"],
  prize: "Competitions & exposure",
  stipend: null,
  startDate: "2026-01-25",
  deadline: "2026-01-10",
  duration: "2 days",
  link: "https://pratibimb.spit.ac.in/",
},

{
  externalId: "fest_sinhgad_karnival_2026",
  title: "Sinhgad Karnival 2026",
  organization: "Sinhgad Institutes",
  type: "college-fest",
  location: "Pune",
  domains: ["other"],
  prize: "Prizes & certificates",
  stipend: null,
  startDate: "2026-02-10",
  deadline: "2026-01-30",
  duration: "4 days",
  link: "https://www.sinhgad.edu/",
},

{
  externalId: "fest_impetus_pict_2026",
  title: "Impetus & Concepts PICT 2026",
  organization: "Pune Institute of Computer Technology",
  type: "college-fest",
  location: "Pune",
  domains: ["web development", "ai/ml", "data science", "cybersecurity"],
  prize: "Cash prizes, certificates",
  stipend: null,
  startDate: "2026-02-21",
  deadline: "2026-02-05",
  duration: "3 days",
  link: "https://pict.edu/impetus/",
},

{
  externalId: "fest_melange_vit_2026",
  title: "Melange VIT Pune 2026",
  organization: "Vishwakarma Institute of Technology",
  type: "college-fest",
  location: "Pune",
  domains: ["other"],
  prize: "Cultural competitions & prizes",
  stipend: null,
  startDate: "2026-03-01",
  deadline: "2026-02-15",
  duration: "3 days",
  link: "https://www.vit.edu/melange/",
},

{
  externalId: "fest_mindspark_coep_2025",
  title: "Mindspark COEP 2025",
  organization: "College of Engineering Pune",
  type: "college-fest",
  location: "Pune",
  domains: ["ai/ml", "robotics", "iot"],
  prize: "Cash prizes & certificates",
  stipend: null,
  startDate: "2025-12-11",
  deadline: "2025-11-30",
  duration: "3 days",
  link: "https://www.mindspark.co.in/",
},

{
  externalId: "fest_8th_mile_rvce_2026",
  title: "8th Mile RVCE 2026",
  organization: "RV College of Engineering",
  type: "college-fest",
  location: "Bangalore",
  domains: ["other"],
  prize: "Cultural competitions & recognition",
  stipend: null,
  startDate: "2026-02-07",
  deadline: "2026-01-25",
  duration: "2 days",
  link: "https://rvce.edu.in/",
},

{
  externalId: "fest_amalgam_pesu_2026",
  title: "Amalgam PES University 2026",
  organization: "PES University",
  type: "college-fest",
  location: "Bangalore",
  domains: ["other"],
  prize: "Competitions & prizes",
  stipend: null,
  startDate: "2026-03-05",
  deadline: "2026-02-20",
  duration: "3 days",
  link: "https://pes.edu/amalgam/",
},

{
  externalId: "fest_incident_nitk_2025",
  title: "Incident NITK 2025",
  organization: "NITK Surathkal",
  type: "college-fest",
  location: "Bangalore",
  domains: ["other"],
  prize: "Cultural competitions",
  stipend: null,
  startDate: "2025-11-17",
  deadline: "2025-11-10",
  duration: "4 days",
  link: "https://incident.nitk.ac.in/",
},


/* =====================================================
   🧠 TECH EVENTS (15)
===================================================== */

{
  externalId: "event_google_cloud_next_2026",
  title: "Google Cloud Next India 2026",
  organization: "Google Cloud",
  type: "tech-event",
  location: "Bangalore",
  domains: ["cloud computing", "devops", "ai/ml", "data science"],
  prize: "Networking, certifications, swag",
  stipend: null,
  startDate: "2026-01-22",
  deadline: "2026-01-15",
  duration: "2 days",
  link: "https://cloud.withgoogle.com/next",
},

{
  externalId: "event_microsoft_ignite_india",
  title: "Microsoft Ignite India 2026",
  organization: "Microsoft",
  type: "tech-event",
  location: "Bangalore",
  domains: ["cloud computing", "ai/ml", "cybersecurity", "devops"],
  prize: "Certifications, learning, networking",
  stipend: null,
  startDate: "2026-02-05",
  deadline: "2026-01-25",
  duration: "3 days",
  link: "https://ignite.microsoft.com",
},

{
  externalId: "event_aws_community_day_blr",
  title: "AWS Community Day Bangalore",
  organization: "Amazon Web Services",
  type: "tech-event",
  location: "Bangalore",
  domains: ["cloud computing", "devops", "security"],
  prize: "Certificates, swag",
  stipend: null,
  startDate: "2025-12-14",
  deadline: "2025-12-05",
  duration: "1 day",
  link: "https://aws.amazon.com/events/community-day/",
},

{
  externalId: "event_meta_dev_circles_mumbai",
  title: "Meta Developer Circles Mumbai",
  organization: "Meta",
  type: "tech-event",
  location: "Mumbai",
  domains: ["web development", "mobile development", "ui/ux"],
  prize: "Learning & networking",
  stipend: null,
  startDate: "2025-11-30",
  deadline: "2025-11-25",
  duration: "1 day",
  link: "https://developers.facebook.com/developercircles/",
},

{
  externalId: "event_accenture_ai_day_pune",
  title: "Accenture AI Innovation Day",
  organization: "Accenture",
  type: "tech-event",
  location: "Pune",
  domains: ["ai/ml", "data science", "cloud computing"],
  prize: "Certification & networking",
  stipend: null,
  startDate: "2025-12-08",
  deadline: "2025-11-30",
  duration: "1 day",
  link: "https://www.accenture.com/in-en/careers/events",
},

{
  externalId: "event_infosys_devops_connect",
  title: "Infosys DevOps Connect 2026",
  organization: "Infosys",
  type: "tech-event",
  location: "Bangalore",
  domains: ["devops", "cloud computing"],
  prize: "Learning sessions",
  stipend: null,
  startDate: "2026-01-18",
  deadline: "2026-01-10",
  duration: "1 day",
  link: "https://www.infosys.com/careers/events.html",
},

{
  externalId: "event_ibm_techxchange_mumbai",
  title: "IBM TechXchange Mumbai 2025",
  organization: "IBM",
  type: "tech-event",
  location: "Mumbai",
  domains: ["ai/ml", "data science", "cloud computing", "cybersecurity"],
  prize: "Certificates & learning",
  stipend: null,
  startDate: "2025-12-11",
  deadline: "2025-12-01",
  duration: "2 days",
  link: "https://www.ibm.com/events",
},

{
  externalId: "event_oracle_cloudworld_india",
  title: "Oracle CloudWorld India 2026",
  organization: "Oracle",
  type: "tech-event",
  location: "Bangalore",
  domains: ["cloud computing", "data science", "ai/ml"],
  prize: "Learning & networking",
  stipend: null,
  startDate: "2026-02-12",
  deadline: "2026-02-01",
  duration: "2 days",
  link: "https://www.oracle.com/events/",
},

{
  externalId: "event_zoho_dev_meetup_remote",
  title: "Zoho Developers Meetup",
  organization: "Zoho Corporation",
  type: "tech-event",
  location: "Remote",
  domains: ["web development", "software development"],
  prize: "Learning & certificates",
  stipend: null,
  startDate: "2025-11-22",
  deadline: "2025-11-18",
  duration: "1 day",
  link: "https://www.zoho.com/events/",
},

{
  externalId: "event_flipkart_tech_talks",
  title: "Flipkart Tech Talks Bangalore",
  organization: "Flipkart",
  type: "tech-event",
  location: "Bangalore",
  domains: ["system design", "web development", "data science"],
  prize: "Networking & learning",
  stipend: null,
  startDate: "2025-12-05",
  deadline: "2025-11-28",
  duration: "1 day",
  link: "https://tech.flipkart.com/",
},

{
  externalId: "event_google_devfest_blr",
  title: "Google DevFest Bangalore 2025",
  organization: "Google Developers Group",
  type: "tech-event",
  location: "Bangalore",
  domains: ["android", "web development", "ai/ml"],
  prize: "Certificates & swag",
  stipend: null,
  startDate: "2025-11-16",
  deadline: "2025-11-10",
  duration: "1 day",
  link: "https://developers.google.com/community/devfest",
},

{
  externalId: "event_paytm_product_meet",
  title: "Paytm Product & Tech Meetup",
  organization: "Paytm",
  type: "tech-event",
  location: "Mumbai",
  domains: ["product management", "web development", "data science"],
  prize: "Learning & networking",
  stipend: null,
  startDate: "2025-11-20",
  deadline: "2025-11-15",
  duration: "1 day",
  link: "https://paytm.com/careers",
},

{
  externalId: "event_tcs_techbytes_pune",
  title: "TCS TechBytes Pune",
  organization: "Tata Consultancy Services",
  type: "tech-event",
  location: "Pune",
  domains: ["cloud computing", "ai/ml", "cybersecurity"],
  prize: "Learning sessions",
  stipend: null,
  startDate: "2025-11-18",
  deadline: "2025-11-14",
  duration: "1 day",
  link: "https://www.tcs.com/careers/events",
},

{
  externalId: "event_aws_summit_india_2025",
  title: "AWS Summit India 2025",
  organization: "Amazon Web Services",
  type: "tech-event",
  location: "Mumbai",
  domains: ["cloud computing", "devops", "security"],
  prize: "Certificates & learning",
  stipend: null,
  startDate: "2025-06-06",
  deadline: "2025-05-30",
  duration: "1 day",
  link: "https://aws.amazon.com/events/summits/",
},

{
  externalId: "event_nvidia_ai_conf_india",
  title: "NVIDIA AI Conference India 2025",
  organization: "NVIDIA",
  type: "tech-event",
  location: "Bangalore",
  domains: ["ai/ml", "data science", "computer vision"],
  prize: "Learning & networking",
  stipend: null,
  startDate: "2025-07-18",
  deadline: "2025-07-10",
  duration: "2 days",
  link: "https://www.nvidia.com/en-in/events/",
},

/* =====================================================
   💼 INTERNSHIPS (15)
===================================================== */

{
  externalId: "intern_tcs_program_2026",
  title: "TCS Internship Program 2026",
  organization: "Tata Consultancy Services",
  type: "internship",
  location: "Mumbai",
  domains: ["web development", "cloud computing", "ai/ml", "data science"],
  prize: "Industry experience",
  stipend: "Paid (varies)",
  startDate: "2026-01-15",
  deadline: "2026-01-05",
  duration: "6–12 weeks",
  link: "https://www.tcs.com/careers/india/internship",
},

{
  externalId: "intern_infosys_winternship_2026",
  title: "Infosys Winternship 2025–26",
  organization: "Infosys",
  type: "internship",
  location: "Pune",
  domains: ["web development", "mobile development", "cloud computing"],
  prize: "Certificate + training",
  stipend: "Paid",
  startDate: "2025-12-01",
  deadline: "2025-11-15",
  duration: "76 days",
  link: "https://www.infosys.com/careers/internships.html",
},

{
  externalId: "intern_pmis_2026",
  title: "Prime Minister Internship Scheme 2026",
  organization: "Government of India",
  type: "internship",
  location: "Mumbai",
  domains: ["all domain"],
  prize: "Government-backed internship",
  stipend: "₹5,000/month",
  startDate: "2026-02-01",
  deadline: "2025-12-31",
  duration: "6–12 months",
  link: "https://pminternship.mca.gov.in",
},

{
  externalId: "intern_cyberzero_remote",
  title: "CyberZero Technology Internship",
  organization: "CyberZero",
  type: "internship",
  location: "Remote",
  domains: ["cybersecurity", "cloud computing", "ai/ml", "devops"],
  prize: "Mentorship + certificate",
  stipend: null,
  startDate: "2026-01-10",
  deadline: "2026-01-05",
  duration: "2–3 months",
  link: "https://cyberzero.in/internship.php",
},

{
  externalId: "intern_igeeks_tech_blr",
  title: "Igeeks Technologies Internship Program",
  organization: "Igeeks Technologies",
  type: "internship",
  location: "Bangalore",
  domains: ["ai/ml", "data science", "web development"],
  prize: "Certificate",
  stipend: "₹3,000/month (select tracks)",
  startDate: "2026-01-20",
  deadline: "2026-01-10",
  duration: "1–3 months",
  link: "https://igeekstechnologies.com",
},

{
  externalId: "intern_webasha_6week_pune",
  title: "WebAsha 6-Week Technology Internship",
  organization: "WebAsha Technologies",
  type: "internship",
  location: "Pune",
  domains: ["cybersecurity", "data science", "cloud computing"],
  prize: "Certificate",
  stipend: null,
  startDate: "2026-02-01",
  deadline: "2026-01-20",
  duration: "6 weeks",
  link: "https://training.webasha.com/6-weeks-internship",
},

{
  externalId: "intern_redhat_swe_2026",
  title: "Red Hat Software Engineering Internship",
  organization: "Red Hat",
  type: "internship",
  location: "Pune",
  domains: ["software development", "cloud computing", "devops"],
  prize: "Enterprise experience",
  stipend: "₹35,000/month",
  startDate: "2026-02-15",
  deadline: "2026-02-05",
  duration: "3 months",
  link: "https://freshershunt.in/red-hat-internship-2026/",
},

{
  externalId: "intern_qualcomm_india_2026",
  title: "Qualcomm India Internship Program",
  organization: "Qualcomm",
  type: "internship",
  location: "Bangalore",
  domains: ["mobile development", "ai/ml", "data science"],
  prize: "Corporate exposure",
  stipend: "Paid",
  startDate: "2026-03-01",
  deadline: "2026-02-20",
  duration: "2–6 months",
  link: "https://www.qualcomm.com/company/careers/internships-and-early-in-career-opportunities/india",
},

{
  externalId: "intern_internshala_ai_track",
  title: "AI & Data Science Internship Track",
  organization: "Internshala",
  type: "internship",
  location: "Remote",
  domains: ["ai/ml", "data science"],
  prize: "Certificate",
  stipend: "Varies",
  startDate: "2026-01-05",
  deadline: "2026-01-20",
  duration: "1–3 months",
  link: "https://internshala.com/internships/artificial-intelligence-ai-internship",
},

{
  externalId: "intern_technoml_remote",
  title: "TechnoML Remote Internship Program",
  organization: "TechnoML",
  type: "internship",
  location: "Remote",
  domains: ["web development", "mobile development", "ui/ux"],
  prize: "Certificate + rewards",
  stipend: null,
  startDate: "2026-01-10",
  deadline: "2026-01-05",
  duration: "1–2 months",
  link: "https://www.technoml.in/internship/",
},

{
  externalId: "intern_prodigy_infotech",
  title: "Prodigy InfoTech Student Internship",
  organization: "Prodigy InfoTech",
  type: "internship",
  location: "Mumbai",
  domains: ["web development", "ai/ml", "data science"],
  prize: "Certificate",
  stipend: null,
  startDate: "2026-02-01",
  deadline: "2026-01-20",
  duration: "1–3 months",
  link: "https://prodigyinfotech.dev/",
},

{
  externalId: "intern_aicte_portal_2026",
  title: "AICTE National Internship Portal 2026",
  organization: "AICTE",
  type: "internship",
  location: "Mumbai",
  domains: ["all domain"],
  prize: "Government-certified internships",
  stipend: "Paid / Unpaid",
  startDate: "2026-01-10",
  deadline: "2026-01-05",
  duration: "1–6 months",
  link: "https://internships.aicte-india.org",
},

{
  externalId: "intern_ibm_past_2024",
  title: "IBM Student Internship Program 2024",
  organization: "IBM",
  type: "internship",
  location: "Bangalore",
  domains: ["web development", "data science"],
  prize: "Industry experience",
  stipend: "Paid",
  startDate: "2024-07-01",
  deadline: "2024-06-10",
  duration: "3 months",
  link: "https://www.ibm.com/in-en/careers/internships",
},

{
  externalId: "intern_ait_pune_students",
  title: "AIT Pune Student Internship Program",
  organization: "Army Institute of Technology",
  type: "internship",
  location: "Pune",
  domains: ["web development", "software development"],
  prize: "Academic internship",
  stipend: "Varies",
  startDate: "2025-01-10",
  deadline: "2024-12-15",
  duration: "1–3 months",
  link: "https://mmit.edu.in/wp-content/uploads/2025/06/Internship-Data-of-A.Y.-2024-25.pdf",
},

{
  externalId: "intern_webasha_summer_2025",
  title: "WebAsha Summer Cybersecurity Internship",
  organization: "WebAsha Technologies",
  type: "internship",
  location: "Pune",
  domains: ["cybersecurity", "ethical hacking"],
  prize: "Certificate",
  stipend: null,
  startDate: "2025-06-01",
  deadline: "2025-05-15",
  duration: "6–8 weeks",
  link: "https://training.webasha.com/summer-training-in-pune.php",
},

/* =====================================================
   🚀 HACKATHONS (15)
===================================================== */

{
  externalId: "hack_mumbaihacks_2025",
  title: "MumbaiHacks 2025",
  organization: "Tech Entrepreneurs Association of Mumbai",
  type: "hackathon",
  location: "Mumbai",
  domains: ["ai/ml", "web development", "cloud computing", "blockchain"],
  prize: "₹1,00,00,000+",
  stipend: null,
  startDate: "2025-11-28",
  deadline: "2025-10-17",
  duration: "2 days",
  link: "https://mumbaihacks.com/",
},

{
  externalId: "hack_build_grow_ai_2026",
  title: "Build & Grow AI Hackathon 2.0",
  organization: "Google Developer Groups Cloud Mumbai",
  type: "hackathon",
  location: "Mumbai",
  domains: ["ai/ml", "cloud computing", "web development"],
  prize: "Prizes + recognition",
  stipend: null,
  startDate: "2026-01-17",
  deadline: "2026-01-10",
  duration: "2 days",
  link: "https://gdg.community.dev/",
},

{
  externalId: "hack_hackdays_pune_2026",
  title: "Hack Days Pune 2026",
  organization: "Major League Hacking",
  type: "hackathon",
  location: "Pune",
  domains: ["ai/ml", "web development", "data science"],
  prize: "Community prizes",
  stipend: null,
  startDate: "2026-01-31",
  deadline: "2026-01-25",
  duration: "1 day",
  link: "https://events.mlh.io/",
},

{
  externalId: "hack_sih_grand_finale_2025",
  title: "Smart India Hackathon Grand Finale 2025",
  organization: "AICTE",
  type: "hackathon",
  location: "Pune",
  domains: ["all domain"],
  prize: "National-level prizes",
  stipend: null,
  startDate: "2025-12-06",
  deadline: "2025-10-31",
  duration: "2 days",
  link: "https://www.sih.gov.in/",
},

{
  externalId: "hack_technothon_ves_2026",
  title: "Technothon 2026",
  organization: "VES Polytechnic",
  type: "hackathon",
  location: "Mumbai",
  domains: ["iot", "embedded systems", "data science"],
  prize: "Prizes & mentorship",
  stipend: null,
  startDate: "2026-02-05",
  deadline: "2026-01-20",
  duration: "24 hours",
  link: "https://www.technothon.in/",
},

{
  externalId: "hack_dynamic_i4c_2025",
  title: "Dynamic Innovation Hackathon",
  organization: "Inclusive Innovations Centre",
  type: "hackathon",
  location: "Pune",
  domains: ["all domain"],
  prize: "₹5,00,000 prize pool",
  stipend: null,
  startDate: "2025-01-17",
  deadline: "2025-02-10",
  duration: "Multi-round",
  link: "https://i4c.in/",
},

{
  externalId: "hack_ncfe_finance_2026",
  title: "NCFE Financial Literacy Hackathon",
  organization: "Inclusive Innovations Centre",
  type: "hackathon",
  location: "Pune",
  domains: ["data science", "cybersecurity", "fintech"],
  prize: "₹7,00,000 prize pool",
  stipend: null,
  startDate: "2025-12-15",
  deadline: "2026-01-10",
  duration: "Multi-round",
  link: "https://i4c.in/",
},

{
  externalId: "hack_ai_innovation_eduverb",
  title: "AI & Innovation Hackathon",
  organization: "Eduverb",
  type: "hackathon",
  location: "Pune",
  domains: ["ai/ml", "web development", "mobile development"],
  prize: "₹1,00,000",
  stipend: null,
  startDate: "2025-10-05",
  deadline: "2025-09-20",
  duration: "3 days",
  link: "https://campus.eduverb.in/hackathons",
},

{
  externalId: "hack_fintech_challenge_eduverb",
  title: "FinTech Innovation Challenge",
  organization: "Eduverb",
  type: "hackathon",
  location: "Mumbai",
  domains: ["blockchain", "ai/ml", "data science"],
  prize: "₹1,50,000",
  stipend: null,
  startDate: "2025-12-03",
  deadline: "2025-11-15",
  duration: "3 days",
  link: "https://campus.eduverb.in/hackathons",
},

{
  externalId: "hack_healthtech_fest_2025",
  title: "HealthTech HackFest",
  organization: "Eduverb",
  type: "hackathon",
  location: "Mumbai",
  domains: ["ai/ml", "iot", "mobile development"],
  prize: "Prizes",
  stipend: null,
  startDate: "2025-12-10",
  deadline: "2025-11-20",
  duration: "3 days",
  link: "https://campus.eduverb.in/hackathons",
},

{
  externalId: "hack_urban_vision_iisc",
  title: "Urban Vision Hackathon",
  organization: "Indian Institute of Science",
  type: "hackathon",
  location: "Bangalore",
  domains: ["ai/ml", "data science"],
  prize: "Prizes",
  stipend: null,
  startDate: "2025-06-21",
  deadline: "2025-06-10",
  duration: "2 days",
  link: "https://kiac.iisc.ac.in/",
},

{
  externalId: "hack_codebot_iisc_2025",
  title: "CodeBot Hackathon 2025",
  organization: "ARTPARK IISc",
  type: "hackathon",
  location: "Bangalore",
  domains: ["ai/ml", "iot"],
  prize: "Prizes",
  stipend: null,
  startDate: "2025-07-17",
  deadline: "2025-07-10",
  duration: "1 day",
  link: "https://www.artpark.in/events",
},

{
  externalId: "hack_eraksha_iit_delhi",
  title: "eRaksha Cybersecurity Hackathon",
  organization: "IIT Delhi",
  type: "hackathon",
  location: "Delhi",
  domains: ["cybersecurity", "ai/ml", "iot"],
  prize: "Cash prizes",
  stipend: null,
  startDate: "2026-01-16",
  deadline: "2026-01-10",
  duration: "36 hours",
  link: "https://home.iitd.ac.in/",
},

{
  externalId: "hack_pkp_mumbai_2025",
  title: "PKP Mumbai Online Hackathon",
  organization: "Programmers Ka Parivar",
  type: "hackathon",
  location: "Mumbai",
  domains: ["web development", "mobile development", "ai/ml"],
  prize: "₹30,000",
  stipend: null,
  startDate: "2025-12-06",
  deadline: "2025-11-30",
  duration: "24 hours",
  link: "https://www.placementpreparation.io/",
},

{
  externalId: "hack_hackindia_series_2025",
  title: "HackIndia National Series 2025",
  organization: "HackIndia.org",
  type: "hackathon",
  location: "Bangalore",
  domains: ["ai/ml", "blockchain", "web development"],
  prize: "$150,000 prize pool",
  stipend: null,
  startDate: "2025-09-01",
  deadline: "2025-08-15",
  duration: "Multi-city series",
  link: "https://hackindia.xyz/",
},

/* =====================================================
   🧑‍💼 JOBS (15)
===================================================== */

{
  externalId: "job_tcs_data_analyst_pune",
  title: "Data Analyst – Data Management & Analytics",
  organization: "Tata Consultancy Services",
  type: "job",
  location: "Pune",
  domains: ["data science", "ai/ml", "cloud computing"],
  prize: "Industry salary",
  stipend: null,
  startDate: "2026-01-01",
  deadline: null,
  duration: "Full-time",
  link: "https://in.linkedin.com/jobs/data-tech-jobs-pune",
},

{
  externalId: "job_ltimindtree_data_scientist_pune",
  title: "Data Scientist – AI/ML & Deep Learning",
  organization: "LTIMindtree",
  type: "job",
  location: "Pune",
  domains: ["data science", "ai/ml"],
  prize: "Industry salary",
  stipend: null,
  startDate: "2026-01-01",
  deadline: null,
  duration: "Full-time",
  link: "https://in.linkedin.com/jobs/data-science-jobs-pune",
},

{
  externalId: "job_pepper_advantage_data_scientist",
  title: "Data Scientist – Financial Analytics",
  organization: "Pepper Advantage",
  type: "job",
  location: "Pune",
  domains: ["data science", "ai/ml"],
  prize: "Industry salary",
  stipend: null,
  startDate: "2025-12-01",
  deadline: null,
  duration: "Full-time",
  link: "https://in.linkedin.com/jobs/data-scientist-jobs-pune",
},

{
  externalId: "job_synechron_data_scientist",
  title: "Enterprise Data Scientist",
  organization: "Synechron",
  type: "job",
  location: "Pune",
  domains: ["data science", "ai/ml"],
  prize: "Industry salary",
  stipend: null,
  startDate: "2025-12-01",
  deadline: null,
  duration: "Full-time",
  link: "https://in.linkedin.com/jobs/data-science-jobs-pune",
},

{
  externalId: "job_onelab_ai_ml_engineer",
  title: "AI/ML Engineer – Applied Intelligence",
  organization: "Onelab Ventures",
  type: "job",
  location: "Pune",
  domains: ["ai/ml", "software development"],
  prize: "Industry salary",
  stipend: null,
  startDate: "2025-12-15",
  deadline: null,
  duration: "Full-time",
  link: "https://in.indeed.com/q-ai-%26-ml-l-maharashtra-jobs.html",
},

{
  externalId: "job_accenture_ai_engineer",
  title: "AI Engineer – Cloud Solutions",
  organization: "Accenture",
  type: "job",
  location: "Pune",
  domains: ["ai/ml", "cloud computing"],
  prize: "Industry salary",
  stipend: null,
  startDate: "2025-12-15",
  deadline: null,
  duration: "Full-time",
  link: "https://in.indeed.com/q-ai-%26-ml-l-maharashtra-jobs.html",
},

{
  externalId: "job_mumbai_data_science_roles",
  title: "Data Science & Analytics Specialist",
  organization: "Deloitte",
  type: "job",
  location: "Mumbai",
  domains: ["data science", "ai/ml"],
  prize: "Industry salary",
  stipend: null,
  startDate: "2025-12-10",
  deadline: null,
  duration: "Full-time",
  link: "https://in.linkedin.com/jobs/ai-developer-data-scientist-jobs-mumbai",
},

{
  externalId: "job_quantanite_ai_backend",
  title: "AI Engineer – Python Backend",
  organization: "Quantanite",
  type: "job",
  location: "Mumbai",
  domains: ["ai/ml", "web development"],
  prize: "Industry salary",
  stipend: null,
  startDate: "2025-12-01",
  deadline: null,
  duration: "Full-time",
  link: "https://in.indeed.com/q-data-scientist-l-navi-mumbai%2C-maharashtra-jobs.html",
},

{
  externalId: "job_cognizant_ai_data_scientist",
  title: "AI/ML Data Scientist",
  organization: "Cognizant",
  type: "job",
  location: "Mumbai",
  domains: ["ai/ml", "data science"],
  prize: "Industry salary",
  stipend: null,
  startDate: "2025-12-01",
  deadline: null,
  duration: "Full-time",
  link: "https://in.indeed.com/q-data-scientist-l-mulund%2C-maharashtra-jobs.html",
},

{
  externalId: "job_bengaluru_ml_engineer",
  title: "Machine Learning Engineer – Applied AI",
  organization: "Product Tech Firms (Bangalore)",
  type: "job",
  location: "Bangalore",
  domains: ["data science", "ai/ml"],
  prize: "Industry salary",
  stipend: null,
  startDate: "2025-12-10",
  deadline: null,
  duration: "Full-time",
  link: "https://in.indeed.com/q-data-scientist-l-bengaluru%2C-karnataka-jobs.html",
},

{
  externalId: "job_interactive_brokers_software_eng",
  title: "Software Engineer – Trading Systems",
  organization: "Interactive Brokers",
  type: "job",
  location: "Mumbai",
  domains: ["web development", "software development"],
  prize: "Industry salary",
  stipend: null,
  startDate: "2025-12-01",
  deadline: null,
  duration: "Full-time",
  link: "https://in.search.yahoo.com/search?p=Interactive+Brokers+software+engineer+jobs+Mumbai",
},

{
  externalId: "job_wipro_ml_engineer",
  title: "Machine Learning Engineer – Enterprise AI",
  organization: "Wipro",
  type: "job",
  location: "Bangalore",
  domains: ["ai/ml", "data science"],
  prize: "Industry salary",
  stipend: null,
  startDate: "2025-12-10",
  deadline: null,
  duration: "Full-time",
  link: "https://in.linkedin.com/jobs/data-science-jobs-pune",
},

{
  externalId: "job_tata_capital_data_analyst",
  title: "Data Analyst – Financial Services",
  organization: "Tata Capital",
  type: "job",
  location: "Mumbai",
  domains: ["data science", "ai/ml"],
  prize: "Industry salary",
  stipend: null,
  startDate: "2025-08-15",
  deadline: "2025-07-31",
  duration: "Full-time",
  link: "https://in.indeed.com/q-tata-capital-%2Cdata-science-l-mumbai%2C-maharashtra-jobs.html",
},

{
  externalId: "job_junior_software_engineer_mumbai",
  title: "Junior Software Engineer – Web Systems",
  organization: "Malaki",
  type: "job",
  location: "Mumbai",
  domains: ["web development", "software development"],
  prize: "Industry salary",
  stipend: null,
  startDate: "2025-02-10",
  deadline: "2025-01-25",
  duration: "Full-time",
  link: "https://internshala.com/jobs/artificial-intelligence-ai-jobs-in-pune-division/",
},

{
  externalId: "job_hdfc_data_analytics",
  title: "Data Analytics Associate – Banking",
  organization: "HDFC Bank",
  type: "job",
  location: "Mumbai",
  domains: ["data science", "analytics"],
  prize: "Industry salary",
  stipend: null,
  startDate: "2025-12-05",
  deadline: null,
  duration: "Full-time",
  link: "https://in.linkedin.com/jobs/data-analyst-jobs-mumbai",
},


];
